wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.3
    cli_version: 0.15.12
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1696446478.052615
    t:
      1:
      - 55
      2:
      - 55
      - 86
      - 95
      - 97
      3:
      - 7
      - 23
      - 51
      4: 3.11.3
      5: 0.15.12
      8:
      - 5
      13: darwin-x86_64
    m:
    - 1: _timestamp
    - 1: usage/total_tokens
      5: 1
      6:
      - 1
      - 3
    - 1: usage/elapsed_time
      5: 1
      6:
      - 1
      - 3
    - 1: usage/completion_tokens
      5: 1
      6:
      - 1
      - 3
    - 1: usage/prompt_tokens
      5: 1
      6:
      - 1
      - 3
